/*
Thumper — Micro Planner
Copyright (c) 2026 Paolo Cioli

[IT] Questo programma è software libero: puoi ridistribuirlo e modificarlo
nei termini della GNU Affero General Public License, versione 3, pubblicata
dalla Free Software Foundation. Vedi il file LICENSE. È distribuito nella
speranza che sia utile, ma SENZA ALCUNA GARANZIA.
Per usi che l'AGPL non consente — per esempio incorporarlo in un prodotto
proprietario o rivenderlo senza rilasciare il sorgente — è disponibile una
licenza commerciale: vedi LICENZA-COMMERCIALE.md.
Sviluppato fuori dalle mansioni assegnate e con
mezzi propri. Strumento di uso generale per uffici, non specifico
di alcuna azienda.

[EN] This program is free software: you can redistribute it and/or modify it
under the terms of the GNU Affero General Public License, version 3, as
published by the Free Software Foundation. See the LICENSE file. It is
distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY.
For uses the AGPL does not allow — such as embedding it in a proprietary
product or reselling it without releasing the source — a commercial licence
is available: see LICENZA-COMMERCIALE.md.
Developed outside assigned duties and with personal
means. A general-purpose tool for offices, not specific to any
one company.
*/
/* ==========================================================
   DIZIONARIO — traduzioni dell'interfaccia
   ----------------------------------------------------------
   Formato:  "testo italiano" : "english text",
   Il testo italiano è la chiave: deve coincidere ESATTAMENTE
   con quello che compare nel programma, accenti compresi.
   {0} {1} ... sono i valori variabili e vanno lasciati.
   Per correggere una traduzione modifica solo la parte destra.
   ========================================================== */
const DIZ = {
"generato il {0}":"generated on {0}",
"Pianificazione":"Planning","Progetti":"Projects","Impostazioni":"Settings",
"Sola lettura":"Read only","Allineato":"Saved","Modifiche non salvate":"Unsaved changes",
"Attiva modifica":"Enable editing","Torna in sola lettura":"Back to read only","Salva":"Save","Apri file…":"Open file…",
"Oggi":"Today","Dal":"From","Al":"To","Periodo":"Period","Larghezza":"Width",
"4 settimane":"4 weeks","8 settimane":"8 weeks","12 settimane":"12 weeks","20 settimane":"20 weeks",
"30 settimane":"30 weeks","52 settimane":"52 weeks","Mese in corso":"Current month",
"Mese precedente":"Previous month","Ultimi 3 mesi":"Last 3 months","Ultimi 6 mesi":"Last 6 months",
"Ultimi 12 mesi":"Last 12 months",
"Compatta":"Compact","Normale":"Normal","Larga":"Wide",
"Progetto":"Project","Tutti i progetti":"All projects","+ Attività":"+ Activity","+ Assenza o smart":"+ Leave or remote",
"Nascondi concluse":"Hide completed","Weekend":"Weekend","Festivi e chiusure":"Holidays and closures",
"Ferie":"Annual leave","Permessi":"Time off","Malattia":"Sick leave","Smart working":"Remote work",
"Trasferta":"Business trip","Deroga":"Exception","✓ Conclusa":"✓ Completed","Conclusa":"Completed",
"✕ Annullata":"✕ Cancelled","Annullata":"Cancelled",
"Persona":"Person","in organico":"on staff","Gruppo":"Group","Anche in":"Also in","h/giorno":"h/day",
"Max smart":"Max remote","Attività":"Activities","Stato":"Status","Attivo":"Active","Non attivo":"Inactive",
"Nome":"Name","Nome e cognome":"Full name","Gruppo principale":"Main group","Ore al giorno":"Hours per day",
"Ore al giorno — part-time":"Hours per day — part-time",
"segue i giorni lavorativi":"follows the working days",
"Vuoto = segue le ore del giorno impostate in Impostazioni. Compila solo se questa persona lavora meno ore di un giorno pieno.":"Empty = follows the day's hours set in Settings. Fill in only if this person works fewer hours than a full day.",
"Anche operativo in":"Also works in",
"In organico":"On staff","Deroga al limite di smart working":"Remote work limit exception",
"Vuoto = limite generale. Compila solo per chi ha un'autorizzazione diversa.":"Empty = general limit. Fill in only for those with a different authorisation.",
"+ Nuova persona":"+ New person","+ Nuova giornata":"+ New entry","+ Nuovo progetto":"+ New project",
"Ferie, permessi e giornate fuori sede":"Leave, time off and days out of office",
"Tipo":"Type","Solo per permessi e trasferte a ore.":"Time off and hourly business trips only.",
"Tutta la giornata":"All day","Deseleziona per indicare solo alcune ore (es. mezza giornata).":"Uncheck to specify only some hours (e.g. half a day).",
"Motivo":"Reason","Motivo (es. guasto all'auto)":"Reason (e.g. car breakdown)",
"Deroga eccezionale, non conta sul limite":"One-off exception, does not count towards the limit",
"Numero":"Number","Numero progetto":"Project number","Riferimento":"Reference","Descrizione":"Description",
"Descrizione (facoltativa)":"Description (optional)","Riferimento (facoltativo)":"Reference (optional)",
"Data di apertura":"Opening date",
"Serve a filtrare per anno.":"Used to filter by year.","Colore sul calendario":"Colour on the calendar",
"Automatico dal numero":"Automatic from the number",
"“A” lascia il colore derivato dal numero di progetto.":"“A” keeps the colour derived from the project number.",
"Gli archiviati restano nel calendario ma spariscono dalle ricerche.":"Archived projects stay on the calendar but disappear from searches.",
"Attiva":"Active","Sospesa":"On hold","Chiusa":"Closed","Archiviata":"Archived",
"Cerca":"Search","Numero, riferimento o descrizione":"Number, reference or description",
"Attive e sospese":"Active and on hold","Tutte":"All","Tutti":"All","Anno":"Year","Ordina per":"Sort by",
"Più recenti":"Most recent","Ore pianificate":"Planned hours","Attività concluse":"Completed activities",
"Solo in ritardo":"Late only","Concluse":"Completed","Periodo pianificato":"Planned period",
"Scheda":"Details","Modifica":"Edit","Fatto":"Done","Modifica progetto":"Edit project","Vedi nel piano":"Show on the plan",
"Chiudi":"Close","Annulla":"Cancel","Elimina":"Delete","Aggiungi":"Add","in corso":"in progress",
"Nessun progetto corrisponde ai filtri.":"No project matches the filters.",
"Ritardo":"Delay","Periodo":"Period","Note":"Notes","Ore":"Hours",
"Nessuna attività pianificata su questo progetto.":"No activity planned on this project.",
"Carico per settimana":"Weekly workload","Nr. giorni over":"No. days over","Giorni in sovraccarico":"Overloaded days",
"Giorno":"Day","Pianificate":"Planned","Disponibili":"Available","Eccesso":"Excess","Causa":"Cause",
"Nessun sovraccarico nel periodo mostrato.":"No overload in the period shown.",
"Opzioni ({0})":"Options ({0})","Applica":"Apply","{0} gg":"{0} days",
"Stessa persona":"Same person","Stesso giorno":"Same day","di margine":"of margin","nessuna scadenza":"no deadline",
"Sposta al {0} (primo giorno libero) → libera {1}h.":"Move to {0} (first free day) → frees up {1}h.",
"Sposta su {0} → libera {1}h.":"Move to {0} → frees up {1}h.",
"Già al limite: nessuno spostamento in avanti è possibile.":"Already at the limit: no move forward is possible.",
"Nessun giorno libero disponibile entro il limite, né un collega con la stessa mansione libero quel giorno.":"No free day available within the limit, nor a colleague with the same role free that day.",
"Attività che occupano questa giornata, ordinate per margine — quanti giorni restano prima del loro limite. Puoi spostare quella che preferisci, di data o di persona.":"Activities occupying this day, ordered by margin — how many days are left before their limit. You can move whichever one you prefer, by date or by person.",
"Nessuno spostamento risolve questa giornata, né di data né di persona. Le attività coinvolte, per capire da dove viene il sovraccarico:":"No move resolves this day, neither by date nor by person. The activities involved, to see where the overload comes from:",
"Attività spostata al {0}":"Activity moved to {0}","Attività riassegnata a {0}":"Activity reassigned to {0}",
"Smart working oltre il limite":"Remote work over the limit","Settimana dal":"Week starting",
"Giorni":"Days","Limite":"Limit","Giorni interessati":"Days involved",
"Deroghe registrate":"Recorded exceptions",
"Tempistiche non rispettate":"Timing not met","Consegna entro":"Due by","Finisce il":"Ends on",
"Tutte le consegne vincolate rientrano.":"All committed deadlines are met.",
"Orario e calendario":"Working time and calendar",
"Coefficiente di efficienza (%)":"Efficiency coefficient (%)",
"Riduce le ore dei giorni lavorativi per ottenere il tempo davvero disponibile a pianificare: Ore × coefficiente. Lascia 100% per nessuna riduzione.":"Reduces the working days' hours to get the time really available to plan: Hours × coefficient. Leave it at 100% for no reduction.",
"Le ore di ogni giorno sono la fonte: valgono per tutti. Chi in anagrafica ha un orario personale più corto (part-time) resta sul proprio; un orario personale più lungo non supera comunque il tetto del giorno.":"Each day's hours are the source: they apply to everyone. Anyone in the staff record with shorter personal hours (part-time) keeps their own; longer personal hours never exceed the day's cap.",
"Giorni lavorativi":"Working days","Lunedì":"Monday","Martedì":"Tuesday","Mercoledì":"Wednesday",
"Giovedì":"Thursday","Venerdì":"Friday","Sabato":"Saturday","Domenica":"Sunday",
"Giorni di smart working a settimana":"Remote working days per week",
"Limite generale. Le deroghe individuali si impostano sulla singola persona.":"General limit. Individual exceptions are set on each person.",
"Archivia i chiusi dopo (giorni)":"Archive closed projects after (days)",
"Chiusure e festività aggiuntive":"Closures and extra holidays",
"Chiusura estiva":"Summer closure","Nessuna chiusura aziendale.":"No company closure.",
"Festività nazionali":"Public holidays",
"domenica":"Sunday","lunedì":"Monday","martedì":"Tuesday","mercoledì":"Wednesday","giovedì":"Thursday",
"venerdì":"Friday","sabato":"Saturday",
"Capodanno":"New Year's Day","Epifania":"Epiphany","Festa della Liberazione":"Liberation Day",
"Festa del lavoro":"Labour Day","Festa della Repubblica":"Republic Day","Ferragosto":"Assumption",
"Ognissanti":"All Saints","Immacolata":"Immaculate Conception","Natale":"Christmas",
"Santo Stefano":"St Stephen's Day","Lunedì dell'Angelo":"Easter Monday",
"Chiusura":"Closure","Chiusura aziendale":"Company closure",
"+ Nuova festività":"+ New holiday","Nuova festività":"New holiday","Modifica festività":"Edit holiday",
"Data fissa":"Fixed date","Relativa a Pasqua":"Relative to Easter",
"N-esimo giorno della settimana":"Nth day of the week",
"Giorni da Pasqua":"Days from Easter",
"Negativo = prima di Pasqua (es. −2 per il Venerdì Santo), positivo = dopo (es. 1 per il Lunedì dell'Angelo).":"Negative = before Easter (e.g. −2 for Good Friday), positive = after (e.g. 1 for Easter Monday).",
"Giorno della settimana":"Day of the week","Occorrenza":"Occurrence","Ultimo":"Last",
"Serve il nome della festività.":"The holiday needs a name.",
"Eliminare questa festività?":"Delete this holiday?",
"Nessuna festività nazionale impostata.":"No public holiday set.",
"Italia":"Italy","Germania":"Germany","USA":"USA",
"Sostituire l'elenco attuale con le {0} festività di {1}?":"Replace the current list with the {0} holidays of {1}?",
"Anteprima":"Preview",
"Nessuna festività per questo anno.":"No holidays for this year.",
"Applica calendario nazionale":"Apply national calendar",
"Paese":"Country","Calendario":"Calendar","Il mio calendario (attivo)":"My calendar (active)",
"Fuso orario: {0}, {1} ({2} in orario estivo).":"Time zone: {0}, {1} ({2} in summer time).",
"Cambia solo cosa vedi qui sotto, non tocca il calendario attivo.":"Only changes what you see below, it doesn't touch the active calendar.",
"Pasqua":"Easter","Pasqua + {0} gg":"Easter + {0} days","Pasqua − {0} gg":"Easter − {0} days",
"ultimo":"last","{0}°":"{0}th","{0} {1} di {2}":"the {0} {1} of {2}",
"Gennaio":"January","Febbraio":"February","Marzo":"March","Aprile":"April","Maggio":"May","Giugno":"June",
"Luglio":"July","Agosto":"August","Settembre":"September","Ottobre":"October","Novembre":"November","Dicembre":"December",
"Dati":"Data","Esporta CSV":"Export CSV","Scarica {0}":"Download {0}","Svuota tutto":"Clear everything",
"mai":"never","Nessuna persona in elenco":"No people on the list","Nessuna persona in elenco.":"No people on the list.",
"Nessuna giornata registrata.":"No entry recorded.",
"Vincolo":"Constraint","Parte il":"Starts on","Consegna entro il":"Due by","Giorno di partenza":"Start day",
"Data di consegna":"Due date","Monte ore":"Total hours",
"Attività conclusa":"Activity completed","Conclusa il":"Completed on",
"Non si farà più. Le ore già spese restano (storia immutabile), quelle future si liberano — come una conclusione anticipata, ma segnalata come annullamento invece che completamento nelle statistiche.":
  "Won't happen anymore. Hours already spent stay (immutable history), future ones are freed — like an early completion, but flagged as a cancellation instead of a completion in the statistics.",
"Non puoi chiudere questo progetto: {0} attività non sono ancora concluse o annullate.":
  "You can't close this project: {0} activities are not yet completed or cancelled.",
"Nuova attività":"New activity","Modifica attività":"Edit activity","Aggiungi attività":"Add activity",
"Salva attività":"Save activity","Nuovo progetto":"New project","Cerca numero o riferimento":"Search number or reference",
"Esiste già un progetto con questo numero: deve essere univoco.":"A project with this number already exists: it must be unique.",
"Crea e seleziona":"Create and select","+ Crea un nuovo progetto":"+ Create a new project",
"Nessun giorno utile":"No available day","Non ci sono abbastanza giorni":"Not enough days",
"Limite superato":"Limit exceeded","Nuova persona":"New person","Modifica persona":"Edit person",
"Modifica giornata":"Edit entry","Ferie, permesso, malattia o smart":"Leave, time off, sick or remote",
"Nuova giornata":"New entry","Anticipare le attività successive?":"Bring forward the next activities?",
"Fai partire la prima dal":"Start the first one on","Non spostare niente":"Move nothing",
"Anticipa le selezionate":"Bring forward the selected ones",
"Le altre selezionate slittano della stessa quantità, mantenendo le distanze tra loro.":"The other selected ones shift by the same amount, keeping the gaps between them.",
"Conclusa nei tempi previsti: non si libera capacità.":"Completed on schedule: no capacity is freed.",
"Attiva la modifica in alto a destra per cambiare questa attività.":"Enable editing at the top right to change this activity.",
"Attiva prima la modifica":"Enable editing first",
"Attiva prima la modifica per aprire questa giornata":"Enable editing first to open this entry",
"Ore pianificate in un giorno non disponibile":"Hours planned on an unavailable day",
"⚠ La partenza cade nel passato.":"⚠ The start falls in the past.",
"Dati caricati":"Data loaded","Ricalcolate le attività a tempo pieno":"Full-time activities recalculated",
"Il file non è leggibile: ":"The file cannot be read: ",
"Salvato in {0}":"Saved to {0}",
"Salvataggio annullato":"Save cancelled",
"Qualcuno ha salvato il piano nel frattempo — il tuo salvataggio è stato annullato per non perdere le sue modifiche.":
  "Someone has saved the plan in the meantime — your save was cancelled so as not to lose their changes.",
"Ricarica l'ultima versione, poi rifai a mano le modifiche che avevi appena fatto.":
  "Reload the latest version, then redo by hand the changes you had just made.",
"Ho capito":"Got it",
"{0} scaricato: spostalo nella cartella di rete sovrascrivendo il vecchio":"{0} downloaded: move it to the network folder, overwriting the old one",
"Scegli un progetto dall'elenco.":"Pick a project from the list.",
"Servono una data e un monte ore maggiore di zero.":"A date and a total of hours greater than zero are required.",
"Serve il nome.":"A name is required.","Serve il numero di progetto.":"A project number is required.",
"Indica il motivo della deroga.":"State the reason for the exception.",
"Controlla le date: la fine non può precedere l'inizio.":"Check the dates: the end cannot precede the start.",
"Controlla le date della chiusura.":"Check the closure dates.",
"Eliminare questa attività?":"Delete this activity?","Eliminare questa persona?":"Delete this person?",
"Eliminare questo progetto?":"Delete this project?",
"Aggiungi prima un progetto in Progetti.":"Add a project first in the Projects tab.",
"Deve partire il {0}":"Must start on {0}",
"1 giornata di lavoro":"1 day of work","{0} giornate di lavoro":"{0} days of work",
"Dal {0} al {1}, {2} h al giorno":"From {0} to {1}, {2} h per day",
" a tempo pieno.":" at full time.",
" Il {0} non è un giorno utile, la partenza slitta al primo disponibile.":" {0} is not a working day, the start moves to the first available one.",
" Weekend, festività e assenze sono già saltati.":" Weekends, holidays and absences are already skipped.",
"Controlla monte ore e giorno di partenza.":"Check the total hours and the start day.",
"Con queste ore la lavorazione non entra prima della data di consegna: riduci il monte ore, alza le ore al giorno o sposta la consegna.":"With these hours the work does not fit before the due date: reduce the total hours, raise the hours per day or move the deadline.",
"Si liberano {0} giornate":"{0} days are freed","Si libera 1 giornata":"1 day is freed",
"Circa {0} h tornano disponibili su {1} dopo il {2}. Al salvataggio ti chiedo se anticipare le attività successive.":"About {0} h become available again for {1} after {2}. On saving I will ask whether to bring forward the next activities.",
"Progetto {0} creato":"Project {0} created",
"{0} attività anticipata":"{0} activity brought forward","{0} attività anticipate":"{0} activities brought forward",
"Questa persona ha {0} attività pianificate che verranno eliminate. Procedere?":"This person has {0} planned activities that will be deleted. Proceed?",
"Questo progetto ha {0} attività pianificate che verranno eliminate. Procedere?":"This project has {0} planned activities that will be deleted. Proceed?",
"Settimana del {0}: {1} giornata su {2}":"Week of {0}: {1} day out of {2}",
"Settimana del {0}: {1} giornate su {2}":"Week of {0}: {1} days out of {2}",
" · {0} in deroga":" · {0} by exception",
"{0} arriverebbe a {1} giornate di smart working nella settimana del {2}, contro un limite di {3}.":"{0} would reach {1} remote working days in the week of {2}, against a limit of {3}.",
"Se è un'eccezione, spunta “Deroga eccezionale” e indica il motivo: il limite resta {0} e la giornata viene registrata a parte.":"If it is an exception, tick “One-off exception” and state the reason: the limit stays {0} and the day is recorded separately.",
"Lavoro fuori sede: ore invariate, ma conta sul limite settimanale.":"Work out of office: hours unchanged, but counts towards the weekly limit.",
"Riduce le ore disponibili del giorno: tutta la giornata, oppure solo le ore indicate.":"Reduces the available hours for the day: all day, or only the hours given.",
"Riduce le ore disponibili del giorno.":"Reduces the available hours for the day.",
"La persona non è disponibile: le attività saltano questi giorni.":"The person is unavailable: activities skip these days.",
"Ci sono modifiche non salvate. Uscire comunque dalla modalità modifica?":"There are unsaved changes. Leave editing mode anyway?",
"Chi sta modificando il piano? (compare come ultimo autore)":"Who is editing the plan? (shown as last author)",
"Dati caricati · {0} archiviate automaticamente":"Data loaded · {0} archived automatically",
"{0} progetto archiviato automaticamente: salva per confermare":"{0} project archived automatically: save to confirm",
"{0} progetti archiviati automaticamente: salva per confermare":"{0} projects archived automatically: save to confirm",
"{0} progetto archiviato":"{0} project archived","{0} progetti archiviati":"{0} projects archived",
"Archiviare {0} progetti chiusi? Restano nel calendario e nello storico, ma non compaiono più nelle ricerche.":"Archive {0} closed projects? They stay on the calendar and in the history, but no longer appear in searches.",
"Archivia i {0} progetti chiusi":"Archive the {0} closed projects",
"Elimina persone, progetti, attività e assenze. I gruppi e le impostazioni restano. Procedere?":"Deletes people, projects, activities and absences. Groups and settings are kept. Proceed?",
"{0} mostrate su {1}":"{0} shown out of {1}","{0} in organico":"{0} on staff",
"Crea il progetto “{0}”":"Create project “{0}”",
"{0} h/giorno":"{0} h/day","{0} gg assenza":"{0} days off","{0} smart":"{0} remote",
"{0} trasf.":"{0} trip","⚠ {0} oltre limite":"⚠ {0} over limit",
"Aggiungi le persone dell'ufficio nella scheda Anagrafiche per iniziare a pianificare.":"Add the office staff in the People tab to start planning.",
"Ultimo salvataggio: {0}":"Last saved: {0}",
"Il tetto generale è di {0} giorni a settimana; le trasferte non rientrano nel conteggio. Chi ha una deroga viene contato sul proprio limite.":"The general cap is {0} days per week; business trips are not counted. Those with an exception are counted against their own limit.",
"Il limite di smart working è di {0} giorni a settimana; ✦ segnala chi ha una deroga personale.":"The remote working limit is {0} days per week; ✦ marks those with a personal exception.",
"{0} ha capacità libera dopo il {1}. Scegli quali lavorazioni anticipare: quelle che lasci ferme restano dove sono.":"{0} has free capacity after {1}. Choose which jobs to bring forward: the ones you leave alone stay where they are.",
"Chiusa il {0}":"Closed on {0}"," · archiviazione tra {0} gg":" · archiving in {0} days",
"Anno {0}":"Year {0}","{0}% delle ore":"{0}% of hours","+{0} gg":"+{0} d",
"di {0}":"of {0}","entro {0}":"by {0}",
"Etichetta informativa: la persona resta su una sola riga, quella del gruppo principale.":"Informational label only: the person stays on a single row, that of the main group.",
"Le sposta fuori dalle ricerche senza toccare lo storico del calendario.":"Moves them out of searches without touching the calendar history.",
"Il piano vive in un file":"The plan lives in a file",
"accanto a questa pagina. Chi apre la pagina vede l'ultimo file salvato.":"next to this page. Whoever opens the page sees the last saved file.",
"Gruppi di lavoro":"Working groups","+ Nuovo gruppo":"+ New group","Nuovo gruppo":"New group",
"Modifica gruppo":"Edit group","Sigla":"Code","Nome del gruppo":"Group name","Ordine":"Order",
"Da 2 a 4 lettere.":"2 to 4 letters.",
"L'ordine qui sotto è l'ordine delle fasce nel calendario. La sigla compare nel calendario e accanto ai nomi.":"The order below is the order of the bands on the calendar. The code appears on the calendar and next to names.",
"Il gruppo ha {0} persone assegnate: spostale in un altro gruppo prima di eliminarlo.":"The group has {0} people assigned: move them to another group before deleting it.",
"Deve restare almeno un gruppo.":"At least one group must remain.",
"Eliminare questo gruppo?":"Delete this group?","Servono sigla e nome del gruppo.":"Group code and name are required.",
"Assegnato a {0} persona: {1}.":"Assigned to {0} person: {1}.",
"Assegnato a {0} persone: {1}.":"Assigned to {0} people: {1}.",
"Mansioni":"Roles","+ Nuova mansione":"+ New role","Nuova mansione":"New role","Modifica mansione":"Edit role",
"Nome della mansione":"Role name","Es. Progettista elettrico":"E.g. Electrical designer",
"Mansione":"Role","— nessuna —":"— none —","— altro nome —":"— other name —",
"Distingue chi, nello stesso gruppo, non fa lo stesso lavoro. Si gestiscono in Organico → Gruppi e mansioni.":"Distinguishes, within the same group, who does different work. Managed in Staff → Groups and roles.",
"Distingue, dentro uno stesso gruppo, chi non fa lo stesso lavoro — usata per capire chi può davvero sostituire chi quando il pianificatore propone una riassegnazione in Verifiche.":"Distinguishes, within the same group, who does different work — used to work out who can genuinely substitute for whom when the planner suggests a reassignment in Checks.",
"Servono sigla e nome della mansione.":"Role code and name are required.",
"Eliminare questa mansione?":"Delete this role?",
"{0} persone hanno questa mansione: resteranno senza. Procedere?":"{0} people have this role: they will be left without one. Proceed?",
"Assegnata a {0} persona: {1}.":"Assigned to {0} person: {1}.",
"Assegnata a {0} persone: {1}.":"Assigned to {0} people: {1}.",
"Nessuna mansione: le riassegnazioni suggerite proporranno solo spostamenti di data, mai di persona.":"No roles: suggested reassignments will only propose date moves, never a change of person.",
"Nessun gruppo.":"No group.",
"Elenco":"List","Tipologie":"Types","+ Nuova tipologia":"+ New type","Nuova tipologia":"New type",
"Modifica tipologia":"Edit type","Nome della tipologia":"Type name","Es. Manutenzione":"E.g. Maintenance",
"Consegna richiesta":"Delivery required","Sì":"Yes",
"Servono sigla e nome della tipologia.":"Type code and name are required.",
"Eliminare questa tipologia?":"Delete this type?",
"{0} progetti hanno questa tipologia: resteranno senza. Procedere?":"{0} projects have this type: they will be left without one. Proceed?",
"Usata da {0} progetto: {1}.":"Used by {0} project: {1}.",
"Usata da {0} progetti: {1}.":"Used by {0} projects: {1}.",
"Nessuna tipologia definita.":"No type defined.",
"Nessuna tipologia: i progetti restano senza classificazione.":"No types: projects stay unclassified.",
"Classifica i progetti (es. per ordine, sviluppo di nuova gamma, manutenzione...): usata nei filtri di Progetti e nelle medie di Verifiche → Tempistiche.":"Classifies projects (e.g. made to order, new range development, maintenance...): used in the Projects filters and in the Checks → Timing averages.",
"Separa le tipologie nelle statistiche dei tempi medi. Si gestiscono in Progetti → Tipologie.":"Separates types in the average time statistics. Managed in Projects → Types.",
"Richiede una consegna concordata":"Requires an agreed delivery date",
"Se attiva, i progetti attivi di questa tipologia senza consegna concordata compaiono come segnalazione nella loro scheda.":"If enabled, active projects of this type with no agreed delivery date show up as a warning on their card.",
"Protezione":"Protection","Protezione attiva":"Protection enabled","Protezione non attiva":"Protection disabled",
"Codice":"Code","Nuovo codice":"New code","Attiva protezione":"Enable protection","Cambia codice":"Change code",
"Rimuovi protezione":"Remove protection","Protezione aggiornata":"Protection updated","Protezione rimossa":"Protection removed",
"Inserisci il codice di protezione:":"Enter the protection code:",
"Codice errato: operazione annullata.":"Wrong code: operation cancelled.",
"Il codice deve avere almeno 4 caratteri.":"The code must be at least 4 characters long.",
"Cambio del codice di protezione.":"Changing the protection code.","Rimozione della protezione.":"Removing the protection.",
"Togliendo {0} dall'organico le sue {1} attività spariscono dal calendario. I dati restano nel file. Procedere?":"Taking {0} off the staff list hides their {1} activities from the calendar. The data stays in the file. Proceed?",
"da salvare":"to be saved","Azioni protette":"Protected actions",
"Eliminare una persona":"Delete a person","Eliminare un progetto":"Delete a project",
"Eliminare un gruppo":"Delete a group","Togliere una persona dall'organico":"Take a person off the staff list",
"Eliminare una singola attività":"Delete a single activity",
"Chiedi il codice anche per eliminare una singola attività":"Ask for the code to delete a single activity too",
"È l'operazione più frequente: attivalo solo se serve davvero.":"It is the most frequent operation: enable it only if you really need to.",
"Attiva la modifica in alto a destra per impostare il codice.":"Enable editing at the top right to set the code.",
"Un codice richiesto prima di eliminare persone, progetti o gruppi, di togliere qualcuno dall'organico e di svuotare tutto. Serve contro il clic distratto: chi apre il file con un editor di testo lo aggira, quindi non usare un codice che usi anche altrove.":"A code required before deleting people, projects or groups, taking someone off the staff list and clearing everything. It guards against a careless click: anyone opening the file in a text editor can bypass it, so do not reuse a code you use elsewhere.",
/* --- Lead time, date limite e modalità finestra --- */
"Lead time e date limite":"Lead times and deadlines",
"Margine di sicurezza (giorni lavorativi)":"Safety margin (working days)",
"Una riga per tipologia di sviluppo interno. La tipologia si assegna poi al singolo progetto, nella sua scheda.":"One row per internal-development type. The type is then assigned to the individual project, on its card.",
"Tempo":"Time",
"Giorni/settimane":"Days/weeks",
"Fornitura est.":"External supply",
"Somma anche la fornitura esterna più lunga al calcolo della scadenza.":"Also adds the longest external supply lead time to the deadline calculation.",
"\"Fornitura est.\" attiva: la scadenza di questa tipologia somma anche la fornitura esterna più lunga. Disattivala per le lavorazioni che non dipendono da fornitori esterni.":"\"External supply\" on: this type's deadline also adds the longest external supply lead time. Turn it off for work that doesn't depend on external suppliers.",
"giorni":"days",
"settimane":"weeks",
"gg":"d",
"sett.":"wk",
"Nessun lead time di fornitura esterna: il calcolo lo considera zero.":"No external-supply lead time: the calculation treats it as zero.",
"Nessuna tipologia: il tempo di sviluppo interno è considerato zero.":"No type: internal-development time is treated as zero.",
"Serve il nome della voce.":"The item needs a name.",
"Il valore deve essere maggiore di zero.":"The value must be greater than zero.",
"{0} attività usano questa tipologia: resteranno senza tempo di sviluppo interno. Procedere?":"{0} activities use this type: they will be left without an internal-development time. Continue?",

"Consegna concordata":"Agreed delivery",
"Facoltativa. La data limite di inizio si calcola dalle attività pianificate su questo progetto (ognuna con la propria tipologia di sviluppo interno), non da qui: si vede in Scheda → “Calcola il giorno ultimo di inizio”.":"Optional. The deadline to start is worked out from the activities planned on this project (each with its own internal-development type), not from here: it's shown in the project card → “Work out the latest start day”.",
"— non indicata —":"— not set —",

"Dal … al … (carico ripartito)":"From … to … (load spread out)",
"Finestra non valida":"Invalid window",
"La data finale deve essere uguale o successiva a quella iniziale.":"The end date must be the same as or later than the start date.",
"La finestra non è valida: la data finale deve essere uguale o successiva a quella iniziale.":"The window is not valid: the end date must be the same as or later than the start date.",
"Nella finestra scelta non ci sono giorni lavorabili per questa persona.":"There are no workable days for this person in the chosen window.",
"{0} h al giorno su {1} giornate utili":"{0} h per day over {1} workable days",
"Dal {0} al {1}: il monte ore è diviso in parti uguali fra i giorni lavorabili, weekend, festività e assenze esclusi.":"From {0} to {1}: the total hours are split evenly across the workable days, excluding weekends, holidays and leave.",
"⚠ Servono più ore di quelle disponibili ({0} h al giorno): la finestra è troppo stretta.":"⚠ It needs more hours than are available ({0} h per day): the window is too tight.",
"Consegna: {0}":"Delivery: {0}",
"Tolti {0} gg di fornitura esterna e {1} gg di sviluppo interno{2}, l'ufficio deve chiudere entro il {3}.":"After {0} days of external supply and {1} days of internal development{2}, the office has to finish by {3}.",
" più {0} gg lavorativi di margine":" plus {0} working days of margin",
"il lead time di fornitura esterna":"the external-supply lead time",
"Nessun lead time di fornitura esterna in tabella: il calcolo lo considera zero (si imposta in Impostazioni).":"No external-supply lead time in the table: the calculation treats it as zero (it's set in Settings).",
"Tipologia di sviluppo interno non indicata qui sopra: il calcolo la considera zero.":"Internal-development type not set above: the calculation treats it as zero.",
"Ultimo giorno utile per partire: {0}":"Latest possible start day: {0}",
"⚠ Con la partenza attuale si arriva in ritardo.":"⚠ With the current start date it will be late.",
"⚠ Con questo monte ore non si rientra più nella data limite.":"⚠ With these hours the deadline can no longer be met.",
"Vincola alla data limite":"Tie it to the deadline",
"Consegna entro il {0}":"Due by {0}",
"Finestra dal {0} al {1}, carico ripartito":"Window from {0} to {1}, load spread out",
"Parte il {0}":"Starts on {0}",

"Calcola il giorno ultimo di inizio":"Work out the latest start day",
"Risale dalla consegna concordata togliendo sviluppo interno e fornitura esterna.":"It works back from the agreed delivery date, subtracting internal development and external supply.",
"Serve la consegna concordata: si imposta con “Modifica progetto”.":"It needs the agreed delivery date: set it with “Edit project”.",
"Manca la consegna concordata":"The agreed delivery date is missing",
"Nessuna scadenza calcolabile":"No deadline can be worked out yet",
"La data limite si calcola dalle attività pianificate su questo progetto, ciascuna con la propria tipologia di sviluppo interno — non dal progetto stesso: aggiungine almeno una.":"The deadline is worked out from the activities planned on this project, each with its own internal-development type — not from the project itself: add at least one.",
"La più stretta fra le attività pianificate su questo progetto.":"The tightest among the activities planned on this project.",
"Date limite a ritroso dalla consegna":"Deadlines working back from delivery",
"Sviluppo interno":"Internal development",
"Fornitura esterna (lead time maggiore)":"External supply (longest lead time)",
"Margine di sicurezza":"Safety margin",
"tipologia non indicata":"type not set",
"tabella vuota":"table empty",
"Inizio pianificato":"Planned start",
"Ultimo inizio utile":"Latest possible start",
"Scarto":"Gap",
"non ci sta":"does not fit",
"{0} gg di margine":"{0} days spare",
"Nessuna attività pianificata: l'ultimo inizio si calcola quando inserisci il monte ore.":"No activity planned: the latest start is worked out once you enter the total hours.",
"Ogni attività è valutata da sola, al ritmo con cui è pianificata. Se le lavorazioni devono seguirsi una dopo l'altra, l'inizio reale va anticipato di conseguenza.":"Each activity is assessed on its own, at the pace it is planned at. If the jobs have to follow one another, the real start has to be brought forward accordingly.",
"⚠ Il piano attuale finisce il {0}, ovvero {1} giorni oltre la data limite.":"⚠ The current plan ends on {0}, that is {1} days past the deadline.",
"Consegna {0}":"Delivery {0}",

"Attività a rischio":"Activities at risk",
"non calcolabile":"can't be worked out yet",
"Consegna":"Delivery",
"Fine ufficio entro":"Office finished by",
"Fine pianificata":"Planned end",
"Oltre di":"Past by",
"non pianificata":"not planned",
"Tutte le consegne concordate rientrano nei tempi.":"All agreed deliveries are on schedule.",
"⚠ +{0} gg":"⚠ +{0} d",
"Il piano finisce oltre la data limite":"The plan ends past the deadline",
"− {0} gg":"− {0} d",
"− {0} gg lavorativi":"− {0} working d",
"{0} · {1}":"{0} · {1}",
"Finestra ripartita":"Spread window",
/* --- Natura della commessa e tempi medi --- */
"Per ordine":"Made to order",
"Sviluppo nuova gamma":"New range development",
"Per tipologia":"By type",
"Tipologia":"Type",
"Tipologia del progetto":"Type of project",
"— da indicare —":"— to be set —",
"Da indicare":"To be set",
"Media tempistiche":"Average timing",
"Sono medie delle ore stimate in pianificazione, non di ore consuntivate: qui dentro nessuno registra il tempo realmente speso.":"These are averages of the hours estimated at planning time, not of actual hours: nobody records the time really spent in here.",
"Concluse":"Completed",
"Ore per progetto":"Hours per project",
"Da / a":"From / to",
"Durata":"Duration",
"⚠ Un progetto concluso non ha la tipologia indicata e resta fuori dal conto. Si imposta nella scheda del progetto, campo “Tipologia”.":"⚠ One completed project has no type set and is left out of the count. It is set on the project card, “Type” field.",
"⚠ {0} progetti conclusi non hanno la tipologia indicata e restano fuori dal conto. Si imposta nella scheda del progetto, campo “Tipologia”.":"⚠ {0} completed projects have no type set and are left out of the count. It is set on the project card, “Type” field.",
"Ore per gruppo, quando il gruppo è coinvolto":"Hours per group, when the group is involved",
"valori singoli":"individual values",
"nessuna":"none",
"su {0} progetti":"over {0} projects",
"{0} sett":"{0} wk",
"{0} h":"{0} h",
/* --- Riorganizzazione schede --- */
"Organico":"Staff",
"Calendario e orario":"Calendar and working time",
"Archivio e dati":"Archive and data",
"Cartelle collegate":"Linked folders",
"Le cartelle archivio che contengono i progetti: da qui la cartella di ogni commessa si trova da sola in base al numero. Il collegamento vale per questa sessione; il browser lo ricorda e lo ripropone con un clic al prossimo avvio.":"The archive folders that contain the projects: from here each project's folder is found on its own, by number. The link lasts for this session; the browser remembers it and offers it again with one click at the next launch.",
"Collegata":"Linked",
"Da confermare":"Needs confirming",
"Rimuovi":"Remove",
"Riprendi":"Resume",
"Dimentica":"Forget",
"Cartella":"Folder",
"Nessuna cartella collegata.":"No folder linked.",
"Aggiungi cartella":"Add folder",
"Riprendi tutte ({0})":"Resume all ({0})",
"Collegamento ripreso: {0}":"Link resumed: {0}",
"Cartella scollegata: {0}":"Folder unlinked: {0}",
"Cartella dimenticata: {0}":"Folder forgotten: {0}",
"Archiviazione automatica":"Automatic archiving",
"All'apertura del file i progetti oltre soglia passano in archivio da soli. Metti 0 per disattivare.":"When the file is opened, projects past the threshold move to the archive on their own. Set 0 to switch it off.",
/* --- Scheda Verifiche e spostamento smart working --- */
"Verifiche":"Checks",
"Carichi e capacità":"Workload and capacity",
"Tempistiche":"Timing",
"Questi conteggi guardano tutti i progetti disponibili e non dipendono dal periodo mostrato nel calendario.":"These figures look at every available project and do not depend on the period shown on the calendar.",
"Il controllo guarda tutte le giornate registrate, passate e future, non un periodo scelto.":"The check looks at every recorded day, past and future, not at a chosen period.",
"Nessuno sforamento registrato.":"No breach recorded.",
"Nessuna deroga registrata.":"No exception recorded.",
/* --- Ore per giorno della settimana --- */
"giorno non lavorativo":"non-working day","persona assente":"person absent","giorno festivo":"public holiday",
"oltre capacità":"over capacity",
"in media {0} h al giorno su {1} giornate utili":"on average {0} h per day over {1} workable days",
"Dal {0} al {1}: il monte ore è ripartito in proporzione alle ore disponibili, perché non tutti i giorni ne hanno altrettante.":"From {0} to {1}: the total hours are split in proportion to the hours available, because not every day has the same.",

/* --- scheda commessa ampliata --- */
"Ore concluse":"Completed hours",
"Risorsa":"Resource",
"Date":"Dates",
"Note e decisioni":"Notes and decisions",
"Documenti":"Documents",
"Segnalazioni":"Warnings",
"Nessuna segnalazione.":"No warnings.",
"Cartella non collegata.":"Folder not connected.",
"Collega cartella":"Connect folder",
"La consegna più critica sfora di {0} giorni.":"The most critical due date is overrun by {0} days.",
"Il piano supera la consegna concordata.":"The plan runs past the agreed delivery date.",
"Consegna non indicata.":"Delivery date not set.",
"Progetto attivo senza nessuna attività pianificata.":"Active project with no planned activity.",
"Progetto chiuso con {0} attività non concluse.":"Project closed with {0} unfinished activities.",

/* --- cartella e documenti della commessa --- */
"Copia percorso":"Copy path",
"Percorso":"Path",
"Percorso copiato":"Path copied",
"Percorso salvato":"Path saved",
"Serve per aprire i file nel loro programma: il browser non lo sa da solo.":"Needed to open files in their own program: the browser cannot know it by itself.",
"Il permesso di lettura scade quando chiudi la pagina: va ridato a ogni apertura.":"Read permission expires when you close the page: it must be granted again each time.",
"Le note vivono nel file appunti dentro la cartella del progetto. Collega la cartella per vederle.":"Notes live in the notes file inside the project folder. Connect the folder to see them.",
"Lettura in corso…":"Reading…",
"Cartella vuota.":"Empty folder.",
"elemento":"item",
"elementi":"items",
"Apri":"Open",
"Nessuna nota nel file appunti.":"No notes in the notes file.",
"Nessun file appunti nella cartella.":"No notes file in the folder.",
"Crea il file note":"Create the notes file",
"File note creato":"Notes file created",
"Aggiungi una nota…":"Add a note…",
"Nota salvata nel file appunti":"Note saved to the notes file",
"Non riesco a leggere la cartella: ":"I cannot read the folder: ",
"Non riesco a creare il file: ":"I cannot create the file: ",
"Questo browser non sa leggere le cartelle. Servono Chrome o Edge.":"This browser cannot read folders. Chrome or Edge are required.",
"Cambia cartella":"Change folder",
"Permesso negato":"Permission denied",
"Cerco {0} dentro {1}…":"Looking for {0} inside {1}…",
"Dentro {0} non trovo nessuna cartella che inizi per {1}":"Inside {0} I find no folder starting with {1}",
"Collega una volta sola la cartella che contiene tutti i progetti: i singoli si trovano da soli.":"Connect the folder containing all projects just once: the individual ones are found automatically.",
"in {0}":"in {0}",
"Collega cartelle":"Connect folders",
"Manuale":"User manual","Apre il manuale utente in una nuova scheda":"Opens the user manual in a new tab",
"Lingua":"Language","Altre azioni":"More actions",
"Cartelle: {0}":"Folders: {0}",
"Cartelle collegate: {0}":"Folders connected: {0}",
"Collega la cartella che contiene tutti i progetti":"Connect the folder containing all projects",
"Percorso non ancora noto":"Path not known yet",
"Senza percorso i file Office e PDF non si possono aprire: salvalo su un progetto qualsiasi e gli altri si compongono da soli.":"Without the path, Office and PDF files cannot be opened: save it on any one project and the others are composed automatically.",
"Collegate in questa sessione. Premi per aggiungerne un'altra.":"Connected for this session. Press to add another one.",
"Elimina questa nota":"Delete this note",
"Elimino questa nota?":"Delete this note?",
"Nota eliminata":"Note deleted",
"Il file appunti è cambiato nel frattempo: lo rileggo, riprova.":"The notes file changed in the meantime: reloading it, try again.",
"Riprendi cartelle":"Resume folders",
"Collegamento ripreso":"Connection resumed",
"Le cartelle di ieri sono ricordate: un clic per riprenderle.":"Yesterday's folders are remembered: one click to resume them.",
"Non riesco a leggere il file appunti: la nota non è stata salvata.":"I cannot read the notes file: the note was not saved.",
"Qualcuno ha scritto nel file mentre stavi scrivendo: rileggo, la tua nota è ancora nella casella.":"Someone wrote to the file while you were writing: reloading, your note is still in the box.",
"Non riesco a scrivere nel file appunti: ":"I cannot write to the notes file: ",
"Non riesco a leggere il file appunti: ":"I cannot read the notes file: ",
"Il file esiste già: lo rileggo":"The file already exists: reloading it",
"Non riesco ad aprire il file: ":"I cannot open the file: ",
"Report carico":"Load report",
"Carico di lavoro":"Workload",
"Tutto l'ufficio":"Whole office",
"Ore disponibili":"Available hours",
"Saturazione":"Utilisation",
"Persone oltre il 100%":"People over 100%",
"Per persona":"Per person",
"Per settimana":"Per week",
"Stampa / PDF":"Print / PDF",
"CSV scaricato":"CSV downloaded",
"Nessuna persona in questo ambito.":"No people in this scope.",
"Periodo dal {0} al {1} · {2} persone · stampato il {3}":"Period from {0} to {1} · {2} people · printed on {3}",
"Le ore sono quelle pianificate, non consuntivate: il report dice cosa è stato <u>preventivato</u>, non cosa è stato fatto.":"Hours are planned, not actual: the report says what was <u>estimated</u>, not what was done.",
"Gruppo e nome":"Group and name",
"Più carichi prima":"Busiest first",
"Più giorni in sovraccarico":"Most overloaded days",
"non indicata":"not set",
"nessuno sviluppo interno":"no internal development",
"Nessuno sviluppo interno":"No internal development",
"Fornitura esterna":"External supply",
"Determina il lead time di sviluppo interno di questa attività, e la data limite di inizio qui sotto. Anche la documentazione può averne uno proprio (es. tempo di preparazione sul supporto richiesto): aggiungila come voce normale in Impostazioni → Lead time, non è un caso speciale.":"It sets this activity's internal-development lead time, and the deadline to start shown below. Documentation can have its own lead time too (e.g. time to prepare it on the requested medium): add it as a normal entry in Settings → Lead time, it isn't a special case.",
"Chi e cosa":"Who and what",
"Quando":"When",
"Descrizione dell'attività":"Activity description",
"Distingue i lavori diversi della stessa persona sullo stesso progetto.":"Tells apart different pieces of work by the same person on the same project.",
"Testo libero: vincoli, accordi, promemoria.":"Free text: constraints, agreements, reminders.",
"Ore al giorno — deroga":"Hours per day — override",
"vuoto = {0} h come da organico":"empty = {0} h as per staff record",
"Ore complessive del lavoro.":"Total hours for the work.",
"Fine della finestra.":"End of the window.",
"Serve solo col carico ripartito.":"Only used with distributed load.",
"Col carico ripartito il ritmo lo decide la finestra.":"With distributed load the window sets the pace.",
"Sovrascrive le ore giornaliere della persona, solo qui.":"Overrides the person's daily hours, here only.",
"Percorso…":"Path…",
"Con che nome vuoi firmare le note?":"What name do you want to sign notes with?",
"Firmi come {0}":"You are signing as {0}",
"La firma ti verrà chiesta al primo salvataggio":"You will be asked for a signature on first save",
"cambia":"change",
"Serve per aprire i file nel loro programma: il browser non lo sa da solo. Di norma si compone da sé.":"Needed to open files in their own program: the browser cannot know it by itself. It is normally composed automatically.",
"Chi sei?":"Who are you?",
"Entra":"Enter",
"Solo consultazione":"Just looking",
"Scegli o scrivi un nome":"Pick or type a name",
"Ciao {0}":"Hello {0}",
"Fatti riconoscere":"Identify yourself",
"Firmi come {0}. Premi per cambiare.":"You are signing as {0}. Press to change.",
"Il nome firma le note che scrivi e il salvataggio del piano.":"The name signs the notes you write and the saving of the plan.",
"Non è una password: serve a farsi riconoscere dai colleghi.":"It is not a password: it is there so colleagues know who did what.",
"Senza gruppo":"No group",
"{0} persone":"{0} people",
"Gruppi":"Groups","Gruppi e mansioni":"Groups and roles",
"Attività assegnate":"Assigned activities",
"Sforamenti smart":"Remote-work overruns",
"{0} registrate":"{0} recorded",
"Ferie e permessi":"Leave and time off",
"Controlli":"Checks",
"Nessuna attività assegnata.":"No activities assigned.",
"Persona non attiva: non compare nel calendario né nei carichi.":"Person not active: does not appear in the calendar or the load figures.",
"{0} giornate con più ore assegnate di quelle disponibili, nel periodo mostrato.":"{0} days with more hours assigned than available, in the period shown.",
"{0} settimane oltre il limite di smart working.":"{0} weeks over the remote-work limit.",
"{0} attività finiscono oltre la data di consegna richiesta.":"{0} activities end past the requested delivery date.",
"Nel periodo mostrato":"In the period shown",
"Dal {0} al {1}, come impostato in barra.":"From {0} to {1}, as set in the toolbar.",
"Nel mese corrente":"In the current month",
"{0} {1}, indipendentemente dalla finestra impostata in barra.":"{0} {1}, regardless of the window set in the toolbar.",
"{0} in tutto, di cui {1} ancora aperte.":"{0} in total, {1} still open.",
"Mostrate le 40 più recenti.":"Showing the 40 most recent.",
"personale":"personal",
"da impostazioni":"from settings",
"deroga personale":"personal exception",
"limite generale":"general limit",
"deroga smart":"remote exception",
"{0} giorni":"{0} days",
"Giornate fuori sede":"Days away",
"Backlog":"Backlog",
"Da fare":"To do","In corso":"In progress",
"Alta":"High","Media":"Medium","Bassa":"Low",
"Promuovi":"Promote",
"Nessun elemento.":"No items.",
"{0} elementi":"{0} items",
"+ Nuovo elemento":"+ New item",
"Richieste, idee o attività fuori progetto, ancora senza commessa né data. “Promuovi” le trasforma in un'attività pianificata vera e propria.":
  "Requests, ideas or work outside any project, still without a project or a date. “Promote” turns it into a real planned activity.",
"Titolo":"Title","Priorità":"Priority","Responsabile":"Owner",
"Es. Richiesta cliente, idea, task fuori progetto":"E.g. client request, idea, off-project task",
"— nessuno —":"— none —",
"Serve il titolo.":"A title is required.",
"Eliminare questo elemento dal backlog?":"Delete this backlog item?",
"Modifica elemento backlog":"Edit backlog item","Nuovo elemento backlog":"New backlog item",
"Licenza":"Licence"
};
